# get all posts
GET http://localhost:9000/api/posts HTTP/1.1

###

# a new post
POST http://localhost:9000/api/posts HTTP/1.1
Content-Type: application/x-www-form-urlencoded


&title=post 1
&content=content 1

###

# Get post with id 3
GET http://localhost:9000/api/post/1 HTTP/1.1


###

# delete post
DELETE http://localhost:9000/api/post/7 HTTP/1.1

###

# update post
PUT http://localhost:9000/api/post/8 HTTP/1.1
content-type: application/x-www-form-urlencoded

&title=post 30 updated 11aaa
&content=content 3 update

###

# api user
POST http://localhost:9000/api/users HTTP/1.1
content-type: application/x-www-form-urlencoded

&name=root
&username=root
&password=1234

###

# get all users
GET http://localhost:9000/api/users HTTP/1.1

###

# get user with id 1
GET http://localhost:9000/api/user/1 HTTP/1.1

###

# delete user
DELETE http://localhost:9000/api/user/1 HTTP/1.1

###

# update user
PUT http://localhost:9000/api/user/2 HTTP/1.1
content-type: application/x-www-form-urlencoded

&name=root update
&username=root update
&password=12345

###